[gspread]
email = "your-service-account@gserviceaccount.com"
private_key = """-----BEGIN PRIVATE KEY-----
YOUR_LONG_PRIVATE_KEY
-----END PRIVATE KEY-----"""
sheet_id = "https://docs.google.com/spreadsheets/d/1i8yt5bEct6WIB4R-gwjp0NsElDXUvFoDS8_GYcb5SW0/edit?usp=drivesdk"
