[gcp_service_account]
type = "...your json credentials..."
private_key_id = "..."
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "..."
client_id = "..."
...

private_gsheets_url = "https://docs.google.com/spreadsheets/d/YOUR_SHEET_ID"
