[gspread]
project_id = "your_project_id"
private_key_id = "your_private_key_id"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqh...\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account-email@project-id.iam.gserviceaccount.com"
client_id = "..."
client_x509_cert_url = "..."
